### ISSUE TITLE
AUniter causing JMDNS exception and not running test cases

### ISSUE THREAD

**Issue by thehellmaker** [bxparks/AUniter#16]
$ /Users/thehellmaker/Downloads/Arduino.app/Contents/MacOS/Arduino --verify --board esp32:esp32:esp32:PSRAM=disabled,PartitionScheme=default,CPUFreq=240,FlashMode=qio,FlashFreq=80,FlashSize=4M,UploadSpeed=921600,DebugLevel=none --pref 'compiler.cpp.extra_flags=-DAUNITER ' Basic.ino
Loading configuration...
Initializing packages...
Preparing boards...
Verifying...
[JmDNS(fe80-0-0-0-706e-79ff-feb3-4c84-awdl0.local.).State.Timer] WARN javax.jmdns.impl.tasks.state.DNSStateTask - Prober(fe80-0-0-0-706e-79ff-feb3-4c84-awdl0.local.).run() exception 
java.io.IOException: No buffer space available (sendto failed)
	at java.net.PlainDatagramSocketImpl.send(Native Method)
	at java.net.DatagramSocket.send(DatagramSocket.java:693)
	at javax.jmdns.impl.JmDNSImpl.send(JmDNSImpl.java:1618)
	at javax.jmdns.impl.tasks.state.DNSStateTask.run(DNSStateTask.java:131)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
[fe80-0-0-0-706e-79ff-feb3-4c84-awdl0.local..recover()] WARN javax.jmdns.impl.JmDNSImpl - RECOVERING
[JmDNS(fe80-0-0-0-706e-79ff-feb3-4c84-awdl0.local.).State.Timer] WARN javax.jmdns.impl.tasks.state.DNSStateTask - Canceler(fe80-0-0-0-706e-79ff-feb3-4c84-awdl0.local.).run() exception 
java.io.IOException: No buffer space available (sendto failed)
	at java.net.PlainDatagramSocketImpl.send(Native Method)
	at java.net.DatagramSocket.send(DatagramSocket.java:693)
	at javax.jmdns.impl.JmDNSImpl.send(JmDNSImpl.java:1618)
	at javax.jmdns.impl.tasks.state.DNSStateTask.run(DNSStateTask.java:131)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
[JmDNS(fe80-0-0-0-b39a-4277-bf07-9df6-utun0.local.).Timer] WARN javax.jmdns.impl.tasks.resolver.DNSResolverTask - ServiceResolver(fe80-0-0-0-b39a-4277-bf07-9df6-utun0.local.).run() exception 
java.io.IOException: No buffer space available (sendto failed)
	at java.net.PlainDatagramSocketImpl.send(Native Method)
	at java.net.DatagramSocket.send(DatagramSocket.java:693)
	at javax.jmdns.impl.JmDNSImpl.send(JmDNSImpl.java:1618)
	at javax.jmdns.impl.tasks.resolver.DNSResolverTask.run(DNSResolverTask.java:73)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
[fe80-0-0-0-b39a-4277-bf07-9df6-utun0.local..recover()] WARN javax.jmdns.impl.JmDNSImpl - RECOVERING
[JmDNS(fe80-0-0-0-b39a-4277-bf07-9df6-utun0.local.).State.Timer] WARN javax.jmdns.impl.tasks.state.DNSStateTask - Canceler(fe80-0-0-0-b39a-4277-bf07-9df6-utun0.local.).run() exception 
java.io.IOException: No buffer space available (sendto failed)
	at java.net.PlainDatagramSocketImpl.send(Native Method)
	at java.net.DatagramSocket.send(DatagramSocket.java:693)
	at javax.jmdns.impl.JmDNSImpl.send(JmDNSImpl.java:1618)
	at javax.jmdns.impl.tasks.state.DNSStateTask.run(DNSStateTask.java:131)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
[fe80-0-0-0-706e-79ff-feb3-4c84-awdl0.local..recover()] WARN javax.jmdns.impl.DNSStatefulObject$DefaultImplementation - Wait for canceled timed out: DNS: fe80-0-0-0-706e-79ff-feb3-4c84-awdl0.local. [fe80:0:0:0:706e:79ff:feb3:4c84%awdl0/fe80:0:0:0:706e:79ff:feb3:4c84%awdl0] state: canceling 1 task: null
[fe80-0-0-0-706e-79ff-feb3-4c84-awdl0.local..recover()] WARN javax.jmdns.impl.JmDNSImpl - fe80-0-0-0-706e-79ff-feb3-4c84-awdl0.local..recover() Could not recover we are Down!
[fe80-0-0-0-b39a-4277-bf07-9df6-utun0.local..recover()] WARN javax.jmdns.impl.DNSStatefulObject$DefaultImplementation - Wait for canceled timed out: DNS: fe80-0-0-0-b39a-4277-bf07-9df6-utun0.local. [fe80:0:0:0:b39a:4277:bf07:9df6%utun0/fe80:0:0:0:b39a:4277:bf07:9df6%utun0] state: canceling 1 task: null
Sketch uses 205304 bytes (15%) of program storage space. Maximum is 1310720 bytes.
Global variables use 13620 bytes (4%) of dynamic memory, leaving 314060 bytes for local variables. Maximum is 327680 bytes.
======== Summary
ALL PASSED

**Comment by thehellmaker** [comment]
@bxparks  can you please help me out here ?

**Comment by bxparks** [comment]
MacOS is not supported by `auniter.sh`. I haven't attempted to run it on the Mac in many months. In theory, it should be possible to make it work. But I don't really have the motivation to figure out all the (rather annoying) differences between GNU/Linux and BSD commands. And the ArduinoIDE on the Mac seemed to pop up UI dialogs, even when running in "command line" mode. The Java exception is coming from the Arduino IDE. No idea what it means, although it seems to be a warning, rather than a hard error. Sorry that I can't be of more help. (P.S. I'm on vacation, so will be slow to follow up.)

**Comment by bxparks** [comment]
I added better support for MacOS in v1.8 (https://github.com/bxparks/AUniter/releases/tag/v1.8), but it has been tested only on Mojave because that's the last version of MacOS that I have. Maybe that helps you, maybe not. I'm going to close this because I don't think I can help with this any further.
